### ISSUE TITLE
Call to a member function exec_SELECTquery() on null

### ISSUE THREAD

**Issue by Pavitro** [franzholz/tsparser#1]
in …typo3conf/ext/tsparser/lib/class.tx_table_db.php line 1554
in combination with tt_products 2.9.13, table 0.8.0, div2007 1.11.4, TYPO3 10.4.13 and PHP 7.3
(tsparser 0.8.0)

**Comment by franzholz** [comment]
You did not activate the extension typo3db_legacy.

This has nothing to do with the extension tsparser.

**Comment by Pavitro** [comment]
Thanks, that was the problem. Sorry 😊
